<a href="https://colab.research.google.com/github/JoseA003/PROGRAMACION_1/blob/main/Matriz_inversa_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def LU_decomposition(A):  # Usando el mismo codigo para LU de la tarea anterior
    n = len(A)
    L = np.eye(n)  # codigo np.eye es para que L tinga 1's en la diagonal principal
    U = np.zeros((n, n))  #Una matriz de tamaño n*n de ceros para iniciar

    for i in range(n):
      for j in range(i, n):
            s1 = 0
            for k in range(i):
                s1 += L[i, k] * U[k, j]  # la sumatoria para poder hallar U

            U[i, j] = A[i, j] - s1  # este es U

            for j in range(i+1, n):
                s2 = 0
                for k in range(i):
                    s2 += L[j, k] * U[k, i]
                L[j, i] = (A[j, i] - s2) / U[i, i]  # este es L
    return L, U

# Ejemplo
A = np.array([
 [ 2, 1, 3],
 [ 2,-1, 2],
 [ 1, 2, 2]
])

L, U = LU_decomposition(A)
print("La Matriz L es: ")
print(L)
print()
print("La Matriz U es: ")
print(U)

def inversa(A):  # Aqui creo otro def para la inversa
    L, U = LU_decomposition(A)  # usamos los mismos L y U del anterior def
    n = len(A)
    I = np.eye(n)
    inv_A = np.zeros((n, n))

    for i in range(n):
        # Resuelve Ly = I para y
        y = np.linalg.solve(L, I[i, :]) #I[:, i] es para solo tomar las filas de I como vectores

        # Resuelve Ux = y para x
        x = np.linalg.solve(U, y)

        inv_A[:, i] = x  #para que inv_A se construya a partir de los vectores

    return inv_A

inv_A = inversa(A)
print()
print("Matriz inversa:")
print(inv_A)

La Matriz L es: 
[[ 1.    0.    0.  ]
 [ 1.    1.    0.  ]
 [ 0.5  -0.75  1.  ]]

La Matriz U es: 
[[ 2.    1.    3.  ]
 [ 0.   -2.   -1.  ]
 [ 0.    0.   -0.25]]

Matriz inversa:
[[-6.  4.  5.]
 [-2.  1.  2.]
 [ 5. -3. -4.]]


In [ ]:
#experimentando con A[:,i] para la traspuesta
A = np.array([
    [-6, 4],
    [-2, 1],
    [5, -3],
])
n = len(A[0])
for i in range(n):
    b = A[:,i]
    print(b)

[-6 -2  5]
[ 4  1 -3]
